version: "3"
services:
  database:
    container_name: media_service_db
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "media_service_db"
      POSTGRES_USER: "cotlin_user"
      POSTGRES_PASSWORD: "cotlin_password"
