server:
  port:8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/media_service_db
    username: cotlin_user
    password: cotlin_password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true